/**
 * Heading-matched photography catalog.
 * Git paths under /public/photos/sections are the backup source of truth.
 * Cloudflare Images IDs (when uploaded) live in cloudflare-image-ids.json.
 */
export const SITE_IMAGES = {
  'ranch-exterior-dusk': {
    gitPath: '/photos/sections/ranch-exterior-dusk.jpg',
    alt: 'Luxury single-story ranch home at dusk on a pool-sized lot in Homestead West, Northwest Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'interior-great-room': {
    gitPath: '/photos/sections/interior-great-room.jpg',
    alt: 'Open great room and kitchen in a Homestead West luxury ranch home, Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'pool-sized-lot': {
    gitPath: '/photos/sections/pool-sized-lot.jpg',
    alt: 'Pool-sized backyard and covered patio at a Homestead West ranch home in Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'detached-casita': {
    gitPath: '/photos/sections/detached-casita.jpg',
    alt: 'Optional detached casita guest suite behind a Homestead West ranch home in Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'community-streetscape': {
    gitPath: '/photos/sections/community-streetscape.jpg',
    alt: 'New construction ranch home streetscape in Homestead West, Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'red-rock-canyon': {
    gitPath: '/photos/sections/red-rock-canyon.jpg',
    alt: 'Red Rock Canyon National Conservation Area, about 9 miles from Homestead West Las Vegas',
    width: 1920,
    height: 1080,
  },
  'la-madre-foothills': {
    gitPath: '/photos/sections/la-madre-foothills.jpg',
    alt: 'La Madre Mountain foothills west of Homestead West in Northwest Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'luxury-kitchen': {
    gitPath: '/photos/sections/luxury-kitchen.jpg',
    alt: 'Luxury kitchen island in a Homestead West single-story ranch home, Las Vegas',
    width: 1920,
    height: 1080,
  },
  'primary-suite': {
    gitPath: '/photos/sections/primary-suite.jpg',
    alt: 'Primary bedroom suite in a Homestead West ranch home with mountain-view windows',
    width: 1920,
    height: 1080,
  },
  'sales-office': {
    gitPath: '/photos/sections/sales-office.jpg',
    alt: 'Homestead West Las Vegas real estate office at 5592 Dapple Gray Rd, Las Vegas NV 89149',
    width: 1920,
    height: 1080,
  },
  'vip-model-home': {
    gitPath: '/photos/sections/vip-model-home.jpg',
    alt: 'VIP private tour entry at a Homestead West model home in Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'aerial-northwest-lv': {
    gitPath: '/photos/sections/aerial-northwest-lv.jpg',
    alt: 'Aerial view of Northwest Las Vegas new construction near Homestead West zip code 89149',
    width: 1920,
    height: 1080,
  },
  'covered-patio': {
    gitPath: '/photos/sections/covered-patio.jpg',
    alt: 'Covered outdoor living patio at a Homestead West ranch home in Las Vegas',
    width: 1920,
    height: 1080,
  },
  'buyer-consultation': {
    gitPath: '/photos/sections/buyer-consultation.jpg',
    alt: 'New construction buyer consultation with floor plans for Homestead West Las Vegas',
    width: 1920,
    height: 1080,
  },
  'private-tour': {
    gitPath: '/photos/sections/private-tour.jpg',
    alt: 'Private backyard tour of a Homestead West ranch home at sunset in Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'three-car-garage': {
    gitPath: '/photos/sections/three-car-garage.jpg',
    alt: 'Three-car garage and driveway at a Homestead West luxury ranch home in Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'dining-room': {
    gitPath: '/photos/sections/dining-room.jpg',
    alt: 'Dining room in a Homestead West single-story ranch home, Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'nw-shopping-plaza': {
    gitPath: '/photos/sections/nw-shopping-plaza.jpg',
    alt: 'Shopping and dining plaza in Northwest Las Vegas near Homestead West zip code 89149',
    width: 1920,
    height: 1080,
  },
  'medical-campus': {
    gitPath: '/photos/sections/medical-campus.jpg',
    alt: 'Medical campus in Northwest Las Vegas, a short drive from Homestead West at 5592 Dapple Gray Rd',
    width: 1920,
    height: 1080,
  },
  'how-it-works': {
    gitPath: '/photos/sections/how-it-works.jpg',
    alt: 'Floor plans on a kitchen island during a Homestead West buyer consultation in Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'sunset-mountain-views': {
    gitPath: '/photos/sections/sunset-mountain-views.jpg',
    alt: 'Covered patio with mountain sunset views from a Homestead West ranch home in Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'office-exterior-89149': {
    gitPath: '/photos/sections/office-exterior-89149.jpg',
    alt: 'Homestead West sales office exterior in Northwest Las Vegas near 5592 Dapple Gray Rd, 89149',
    width: 1920,
    height: 1080,
  },
  'faq-buyer-desk': {
    gitPath: '/photos/sections/faq-buyer-desk.jpg',
    alt: 'Ranch floor plans and lot map on a desk for Homestead West Las Vegas buyer questions',
    width: 1920,
    height: 1080,
  },
  'for-sale-ranch': {
    gitPath: '/photos/sections/for-sale-ranch.jpg',
    alt: 'Luxury ranch home for sale on a pool-sized lot in Homestead West, Northwest Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'staged-living-room': {
    gitPath: '/photos/sections/staged-living-room.jpg',
    alt: 'Staged living room in a Homestead West single-story ranch home, Las Vegas',
    width: 1920,
    height: 1080,
  },
  'spa-primary-bath': {
    gitPath: '/photos/sections/spa-primary-bath.jpg',
    alt: 'Primary spa bathroom with soaking tub in a Homestead West ranch home, Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'ann-fort-apache-89149': {
    gitPath: '/photos/sections/ann-fort-apache-89149.jpg',
    alt: 'Ann Road and Fort Apache area of Northwest Las Vegas 89149 near Homestead West',
    width: 1920,
    height: 1080,
  },
  'virtual-tour-tablet': {
    gitPath: '/photos/sections/virtual-tour-tablet.jpg',
    alt: '3D virtual tour of a Homestead West ranch home on a tablet in the kitchen, Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'managed-rental-ranch': {
    gitPath: '/photos/sections/managed-rental-ranch.jpg',
    alt: 'Professionally managed ranch home exterior in Homestead West, Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'dining-patio-89149': {
    gitPath: '/photos/sections/dining-patio-89149.jpg',
    alt: 'Outdoor restaurant patio with Red Rock mountain views near Homestead West, Northwest Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'school-campus-89149': {
    gitPath: '/photos/sections/school-campus-89149.jpg',
    alt: 'School campus building in the Centennial Hills area near Homestead West, Las Vegas NV 89149',
    width: 1920,
    height: 1080,
  },
  'grocery-center-89149': {
    gitPath: '/photos/sections/grocery-center-89149.jpg',
    alt: 'Grocery and shopping center in Northwest Las Vegas near Homestead West zip code 89149',
    width: 1920,
    height: 1080,
  },
  'parking-retail-89149': {
    gitPath: '/photos/sections/parking-retail-89149.jpg',
    alt: 'Retail parking lot at a shopping center in Northwest Las Vegas near 5592 Dapple Gray Rd',
    width: 1920,
    height: 1080,
  },
  'vs-skye-canyon': {
    gitPath: '/photos/sections/vs-skye-canyon.jpg',
    alt: 'Luxury Homestead West ranch home with pool in the foreground and a hillside master-planned community beyond, Northwest Las Vegas',
    width: 1920,
    height: 1080,
  },
  'cadence-henderson': {
    gitPath: '/photos/sections/cadence-henderson.jpg',
    alt: 'Two-story new-construction streetscape in a Henderson master-planned community, compared with Homestead West ranch homes',
    width: 1920,
    height: 1080,
  },
  'appointment-consultation': {
    gitPath: '/photos/sections/appointment-consultation.jpg',
    alt: 'Homestead West buyer appointment desk with ranch floor plans and a model-home view in Northwest Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'listings-search-desk': {
    gitPath: '/photos/sections/listings-search-desk.jpg',
    alt: 'Laptop search for Homestead West MLS listings on a kitchen island in a Northwest Las Vegas ranch home',
    width: 1920,
    height: 1080,
  },
  'home-style-ranch': {
    gitPath: '/photos/sections/home-style-ranch.jpg',
    alt: 'Single-story ranch great room opening to a covered patio in Homestead West, Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'commute-northwest': {
    gitPath: '/photos/sections/commute-northwest.jpg',
    alt: 'Northwest Las Vegas freeway interchange and desert mountains near Homestead West zip code 89149',
    width: 1920,
    height: 1080,
  },
  'price-comparison-ranch': {
    gitPath: '/photos/sections/price-comparison-ranch.jpg',
    alt: 'Luxury single-story ranch home on a pool-sized lot in Homestead West, Northwest Las Vegas from $910K',
    width: 1920,
    height: 1080,
  },
  'tenant-keys-ranch': {
    gitPath: '/photos/sections/tenant-keys-ranch.jpg',
    alt: 'Managed Homestead West ranch porch with lockbox and keys in Northwest Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'investment-roi': {
    gitPath: '/photos/sections/investment-roi.jpg',
    alt: 'Investment analysis desk with ranch cash-flow worksheets overlooking Northwest Las Vegas mountains',
    width: 1920,
    height: 1080,
  },
  'preapproval-desk': {
    gitPath: '/photos/sections/preapproval-desk.jpg',
    alt: 'Mortgage pre-approval documents on a dining table in a Homestead West ranch kitchen, Las Vegas',
    width: 1920,
    height: 1080,
  },
  'local-park-89149': {
    gitPath: '/photos/sections/local-park-89149.jpg',
    alt: 'Neighborhood park with walking paths near Homestead West in Northwest Las Vegas 89149',
    width: 1920,
    height: 1080,
  },
  'bhhs-office-interior': {
    gitPath: '/photos/sections/bhhs-office-interior.jpg',
    alt: 'Real estate office interior overlooking ranch homes near 5592 Dapple Gray Rd, Las Vegas NV 89149',
    width: 1920,
    height: 1080,
  },
} as const

export type SiteImageId = keyof typeof SITE_IMAGES

/** Default image for each route H1 (GBP / local SEO alt text lives on the asset). */
export const PAGE_HERO_IMAGE: Record<string, SiteImageId> = {
  '/': 'ranch-exterior-dusk',
  '/properties': 'for-sale-ranch',
  '/floor-plans': 'interior-great-room',
  '/floor-plans/3336': 'luxury-kitchen',
  '/floor-plans/3704': 'detached-casita',
  '/community': 'sunset-mountain-views',
  '/community-map': 'aerial-northwest-lv',
  '/virtual-tour': 'virtual-tour-tablet',
  '/location': 'office-exterior-89149',
  '/location/las-vegas-office': 'office-exterior-89149',
  '/contact': 'buyer-consultation',
  '/about': 'bhhs-office-interior',
  '/buyers-guide': 'buyer-consultation',
  '/homebuying-process': 'how-it-works',
  '/vip-buyer-program': 'vip-model-home',
  '/faq': 'faq-buyer-desk',
  '/testimonials': 'private-tour',
  '/reviews': 'sales-office',
  '/amenities': 'local-park-89149',
  '/directions': 'ann-fort-apache-89149',
  '/appointment': 'appointment-consultation',
  '/services': 'buyer-consultation',
  '/services/buying': 'private-tour',
  '/services/selling': 'for-sale-ranch',
  '/services/investment': 'investment-roi',
  '/services/property-management': 'tenant-keys-ranch',
  '/northwest-las-vegas-new-construction': 'community-streetscape',
  '/homestead-west-vs-skye-canyon': 'vs-skye-canyon',
  '/homestead-west-vs-cadence': 'cadence-henderson',
  '/la-madre-foothills': 'la-madre-foothills',
  '/blog': 'covered-patio',
}
